tz: updated coding style from 2008 to 2021

diff --git a/tz b/tz
--- a/tz
+++ b/tz
@@ -13,14 +13,15 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-set -u;
+set -u -e -C
+shopt -s failglob nullglob
 
-version='2020-Jan-10';
+version='2021-Nov-7'
 
 
 
 # Default compressor and extension
-zip='zstd'; ext='zst';
+zip='zstd'; ext='zst'
 
 
 
@@ -34,12 +35,12 @@ function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
 # Prompt the user and wait for 'yes' or 'no'.
 
 function askYesNo { # args: <Question string>
-  while read -p $'\e[34m'"$* [yes/no] "$'\e[m' answer; do
-    test "$answer" = yes && return 0;
-    test "$answer" = no && return 1;
-    echo -e 'Please type either "yes" or "no".'
-  done;
-  error "Failed to read answer.";
+    while read -p $'\e[34m'"$* [yes/no] "$'\e[m' answer; do
+        test "${answer}" = yes && return 0
+        test "${answer}" = no && return 1
+        echo -e 'Please type either "yes" or "no".'
+    done
+    error "Failed to read answer."
 }
 
 
@@ -47,10 +48,10 @@ function askYesNo { # args: <Question string>
 # Ask before overwriting a file and remove it if so.
 
 function overwrite { # args: <filename>
-    test -e "$1" || return 0;
-    askYesNo "Overwrite ${1}" || return 1;
-    test -w "$1" || error "Cannot write ${1}";
-    rm -rf "$1" || error "Unable to remove ${1}.";
+    test -e "${1}" || return 0
+    askYesNo "Overwrite ${1}" || return 1
+    test -w "${1}" || error "Cannot write ${1}"
+    rm -rf "${1}" || error "Unable to remove ${1}."
 }
 
 
@@ -58,8 +59,8 @@ function overwrite { # args: <filename>
 # Removes list of files, used by 'trap _ exit'
 
 function cleanup { # args: <filename>*
-  echo -e '\nExiting while processing; cleanup required!';
-  echo "Leftovers: $*";
+    echo -e '\nExiting while processing; cleanup required!'
+    echo "Leftovers: $*"
 }
 
 
@@ -67,38 +68,39 @@ function cleanup { # args: <filename>*
 # Decompress an archive.
 
 function doUnzipArch { # args: <source> <unzipper> <target>
-  if overwrite "$3"; then
-    tmp="$(mktemp -d "${3}.XXXXXXXXXX")" || error "mktemp failed.";
-    trap "cleanup '${3}' '${tmp}'" exit;
-    echo "Extracting (tmp=${tmp})";
-    if test "$2" = 'unzip'; then
-        unzip "$1" -d "$tmp" || error 'FAILED';
-    elif test "$2" = 'un7z'; then
-        7z x -o"${tmp}" "${1}" || error "FAILED"
-    else
-        cat "$1" | eval "$2" | tar -k -C "$tmp" -x || error ' FAILED';
-    fi;
-    echo -n 'Policy checking...';
-    if test "$(ls -A "$tmp")" = "$3"; then
-      echo ' done';
+    if overwrite "${3}"; then
+        tmp="$(mktemp -d "${3}.XXXXXXXXXX")" || error "mktemp failed."
+        trap "cleanup '${3}' '${tmp}'" exit
+        echo "Extracting (tmp=${tmp})"
+        if test "${2}" = 'unzip'; then
+            unzip "${1}" -d "${tmp}" || error 'FAILED'
+        elif test "${2}" = 'un7z'; then
+            7z x -o"${tmp}" "${1}" || error "FAILED"
+        else
+            cat "${1}" | eval "${2}" | tar -k -C "${tmp}" -x || error ' FAILED'
+        fi
+        echo -n 'Policy checking...'
+        if test "$(ls -A "${tmp}")" = "${3}"; then
+            echo ' done'
 
-      if mv "${tmp}/${3}" "${3}"; then
-        true;
-      else
-        origMode="$(stat -c "%a" "${tmp}/${3}")" || error "Could not determine file mode.";
-        chmod 700 "${tmp}/${3}" || error "Could not chmod.";
-        mv "${tmp}/${3}" "${3}" || error "Moving from ${tmp} failed.";
-        chmod "$origMode" "$3" || error "Could not chmod.";
-      fi;
-      rm -rf "$tmp" || error "Removing ${tmp} failed.";
+            if mv "${tmp}/${3}" "${3}"; then
+                true
+            else
+                origMode="$(stat -c "%a" "${tmp}/${3}")" \
+                    || error "Could not determine file mode."
+                chmod 700 "${tmp}/${3}" || error "Could not chmod."
+                mv "${tmp}/${3}" "${3}" || error "Moving from ${tmp} failed."
+                chmod "${origMode}" "${3}" || error "Could not chmod."
+            fi
+            rm -rf "${tmp}" || error "Removing ${tmp} failed."
+        else
+            mv "${tmp}" "${3}" || error "Renaming ${tmp} failed."
+            daisies+=("${3}")
+        fi
+        trap - exit
     else
-      mv "$tmp" "$3" || error "Renaming ${tmp} failed.";
-      daisies+=("${3}");
-    fi;
-    trap - exit;
-  else
-    skip+=("${1}");
-  fi;
+        skip+=("${1}")
+    fi
 }
 
 
@@ -106,18 +108,19 @@ function doUnzipArch { # args: <source> <unzipper> <target>
 # Compress a directory.
 
 function doZipDir { # args: <source> <zipper> <target>
-  if overwrite "$3"; then
-    trap "cleanup '${3}'" exit;
-    echo "Compressing into: '${3}'";
-    if test "$2" = 'zip'; then
-        zip -r "$3" "$1" || error 'FAILED';
+  if overwrite "${3}"; then
+    trap "cleanup '${3}'" exit
+    echo "Compressing into: '${3}'"
+    if test "${2}" = 'zip'; then
+        zip -r "${3}" "${1}" || error 'FAILED'
     else
-        tar -C "$(dirname ${1})" -c "$(basename ${1})" | eval "${2}" > "$3" || error 'FAILED';
-    fi;
-    trap - exit;
+        tar -C "$(dirname "${1}")" -c "$(basename "${1}")" \
+            | eval "${2}" > "${3}" || error 'FAILED'
+    fi
+    trap - exit
   else
-    skip+=("${1}");
-  fi;
+    skip+=("${1}")
+  fi
 }
 
 
@@ -125,14 +128,14 @@ function doZipDir { # args: <source> <zipper> <target>
 # Decompress a file.
 
 function doUnzipFile { # args: <source> <unzipper> <target>
-  if overwrite "$3"; then
-    trap "cleanup '${3}'" exit;
-    echo "Extracting";
-    cat "$1" | eval "$2" > "$3" || error " FAILED";
-    trap - exit;
+  if overwrite "${3}"; then
+    trap "cleanup '${3}'" exit
+    echo "Extracting"
+    cat "${1}" | eval "${2}" > "${3}" || error " FAILED"
+    trap - exit
   else
-    skip+=("${1}");
-  fi;
+    skip+=("${1}")
+  fi
 }
 
 
@@ -140,18 +143,18 @@ function doUnzipFile { # args: <source> <unzipper> <target>
 # Compress a file
 
 function doZipFile { # args: <source> <zipper> <target>
-  if overwrite "$3"; then
-    trap "cleanup '${3}'" exit;
-    echo "Compressing into: '${3}'";
-    if test "$2" = 'zip'; then
-        zip "$3" "$1" || error 'FAILED';
+  if overwrite "${3}"; then
+    trap "cleanup '${3}'" exit
+    echo "Compressing into: '${3}'"
+    if test "${2}" = 'zip'; then
+        zip "${3}" "${1}" || error 'FAILED'
     else
-        cat "$1" | eval "${2}" > "$3" || error ' FAILED';
-    fi;
-    trap - exit;
+        cat "${1}" | eval "${2}" > "${3}" || error ' FAILED'
+    fi
+    trap - exit
   else
-    skip+=("${1}");
-  fi;
+    skip+=("${1}")
+  fi
 }
 
 
@@ -243,24 +246,25 @@ There are probably some.  So use at your own risk.  For debugging
 contact Stefan Klinger <http://stefan-klinger.de>.
 
 EOF
-    exit 0;
-fi;
+    exit 0
+fi
 
 
 
 # List of targets that generated a warning.
-daisies=();
+daisies=()
 
 # List of sources not processed on user intervention.
-skip=();
+skip=()
 
 
 
 if test -r "${HOME}/.tzrc"; then
-    echo "Reading defaults from ~/.tzrc";
-    source "${HOME}/.tzrc";
-    test "${version}" = "${forVersion:-unknown}" || error "Unsupported version in '~/.tzrc'";
-fi;
+    echo "Reading defaults from ~/.tzrc"
+    source "${HOME}/.tzrc"
+    test "${version}" = "${forVersion:-unknown}" \
+        || error "Unsupported version in '~/.tzrc'"
+fi
 
 
 
@@ -269,111 +273,154 @@ while test "${1:-}"; do
         case "${1}" in
 
             -b)
-                echo "Using bzip2 for compression.";
-                zip='bzip2 -9'; ext='bz2';;
+                echo "Using bzip2 for compression."
+                zip='bzip2 -9'; ext='bz2'
+                ;;
 
             -g)
-                echo "Using gzip for compression.";
-                zip='gzip -9'; ext='gz';;
+                echo "Using gzip for compression."
+                zip='gzip -9'; ext='gz'
+                ;;
 
             -l)
-                echo 'Using lzma for compression';
-                zip='lzma -9'; ext='lzma';;
+                echo 'Using lzma for compression'
+                zip='lzma -9'; ext='lzma'
+                ;;
 
             -x)
-                echo 'Using xz for compression';
-                zip='xz -9'; ext='xz';;
+                echo 'Using xz for compression'
+                zip='xz -9'; ext='xz'
+                ;;
 
             -s)
-                echo 'Using zstd for compression';
-                zip='zstd -9 --long=31 -T0'; ext='zst';;
+                echo 'Using zstd for compression'
+                zip='zstd -9 --long=31 -T0'; ext='zst'
+                ;;
 
             -z)
-                echo 'Using zip for compression and archive generation';
-                zip='zip'; ext='zip';;
+                echo 'Using zip for compression and archive generation'
+                zip='zip'; ext='zip'
+                ;;
 
             *)
-                error "Do not understand argument '${1}'.";;
-        esac;
+                error "Do not understand argument '${1}'."
+                ;;
+        esac
 
     # compress directory
-    elif test -d "$1"; then
-        echo "Compressing directory ${1}";
-        if test "$zip" = 'zip'; then
-            doZipDir "$1" "$zip" "$(basename "$1").${ext}";
+    elif test -d "${1}"; then
+        echo "Compressing directory ${1}"
+        if test "${zip}" = 'zip'; then
+            doZipDir "${1}" "${zip}" "$(basename "${1}").${ext}"
         else
-            doZipDir "$1" "$zip" "$(basename "$1").tar.${ext}";
-        fi;
+            doZipDir "${1}" "${zip}" "$(basename "${1}").tar.${ext}"
+        fi
 
     # process file
-    elif test -f "$1"; then
-        echo "Processing file ${1}";
-        case "$1" in
+    elif test -f "${1}"; then
+        echo "Processing file ${1}"
+        case "${1}" in
+
+            ### extracting archives ###
 
             # extract and untar bzip2'ed tar archives
-            *.tar.bz2) doUnzipArch "$1" bunzip2 "$(basename "$1" .tar.bz2)";;
-            *.tb2) doUnzipArch "$1" bunzip2 "$(basename "$1" .tb2)";;
-            *.tbz) doUnzipArch "$1" bunzip2 "$(basename "$1" .tbz)";;
+            *.tar.bz2)
+                doUnzipArch "${1}" bunzip2 "$(basename "${1}" .tar.bz2)"
+                ;;
+            *.tb2)
+                doUnzipArch "${1}" bunzip2 "$(basename "${1}" .tb2)"
+                ;;
+            *.tbz)
+                doUnzipArch "${1}" bunzip2 "$(basename "${1}" .tbz)"
+                ;;
 
             # extract and untar gzip'ed tar archives
-            *.tar.gz) doUnzipArch "$1" gunzip "$(basename "$1" .tar.gz)";;
-            *.tgz) doUnzipArch "$1" gunzip "$(basename "$1" .tgz)";;
+            *.tar.gz)
+                doUnzipArch "${1}" gunzip "$(basename "${1}" .tar.gz)"
+                ;;
+            *.tgz)
+                doUnzipArch "${1}" gunzip "$(basename "${1}" .tgz)"
+                ;;
 
             # extract and untar lzma'ed tar archives
-            *.tar.lzma) doUnzipArch "$1" unlzma "$(basename "$1" .tar.lzma)";;
-            *.tlz) doUnzipArch "$1" unlzma "$(basename "$1" .tgz)";;
+            *.tar.lzma)
+                doUnzipArch "${1}" unlzma "$(basename "${1}" .tar.lzma)"
+                ;;
+            *.tlz)
+                doUnzipArch "${1}" unlzma "$(basename "${1}" .tgz)"
+                ;;
 
             # extract and untar xz'ed tar archives
-            *.tar.xz) doUnzipArch "$1" unxz "$(basename "$1" .tar.xz)";;
-            *.txz) doUnzipArch "$1" unxz "$(basename "$1" .txz)";;
+            *.tar.xz)
+                doUnzipArch "${1}" unxz "$(basename "${1}" .tar.xz)"
+                ;;
+            *.txz)
+                doUnzipArch "${1}" unxz "$(basename "${1}" .txz)"
+                ;;
 
             # extract and untar zstd'ed tar archives
-            *.tar.zst) doUnzipArch "$1" 'unzstd --long=31' "$(basename "$1" .tar.zst)";;
-
-            # extract bzip2'ed files
-            *.bz2) doUnzipFile "$1" bunzip2 "$(basename "$1" .bz2)";;
-
-            # extract gzip'ed files
-            *.gz) doUnzipFile "$1" gunzip "$(basename "$1" .gz)";;
-
-            # extract lzma'ed files
-            *.lzma) doUnzipFile "$1" unlzma "$(basename "$1" .lzma)";;
-
-            # extract xz'ed files
-            *.xz) doUnzipFile "$1" unxz "$(basename "$1" .xz)";;
-
-            # extract zstd'ed files
-            *.zst) doUnzipFile "$1" 'unzstd --long=31' "$(basename "$1" .zst)";;
+            *.tar.zst)
+                doUnzipArch \
+                    "${1}" 'unzstd --long=31' "$(basename "${1}" .tar.zst)"
+                ;;
 
             # extract zip archives
-            *.zip) doUnzipArch "$1" unzip "$(basename "$1" .zip)";;
+            *.zip)
+                doUnzipArch "${1}" unzip "$(basename "${1}" .zip)"
+                ;;
 
             # extract 7zip archives
-            *.7z) doUnzipArch "$1" un7z "$(basename "$1" .7z)";;
+            *.7z)
+                doUnzipArch "${1}" un7z "$(basename "${1}" .7z)"
+                ;;
 
-            # compress other files
-            *) doZipFile "$1" "${zip}" "$(basename "$1").${ext}";
+            ### extract non-archive files ###
 
-        esac;
+            *.bz2)
+                doUnzipFile "${1}" bunzip2 "$(basename "${1}" .bz2)"
+                ;;
+
+            *.gz)
+                doUnzipFile "${1}" gunzip "$(basename "${1}" .gz)"
+                ;;
+
+            *.lzma)
+                doUnzipFile "${1}" unlzma "$(basename "${1}" .lzma)"
+                ;;
+
+            *.xz)
+                doUnzipFile "${1}" unxz "$(basename "${1}" .xz)"
+                ;;
+
+            *.zst)
+                doUnzipFile "${1}" 'unzstd --long=31' "$(basename "${1}" .zst)"
+                ;;
+
+            ### compress other files ###
+
+            *)
+                doZipFile "${1}" "${zip}" "$(basename "${1}").${ext}"
+
+        esac
 
     else
-        error "No such file or directory: ${1}";
+        error "No such file or directory: ${1}"
 
-    fi;
-    shift;
-    echo;
-done;
+    fi
+    shift
+    echo
+done
 
 # Print a report.
 
 if test "${#daisies[@]}" -gt 0; then
-    warn 'Grouped some contents under new directory.  Avoid creating such archives!';
-    echo "The delinquents: ${daisies[@]}";
-fi;
+    warn 'Grouped some contents under new directory.  Avoid creating such archives!'
+    echo "The delinquents: ${daisies[@]}"
+fi
 
 if test "${#skip[@]}" -gt 0; then
-    warn 'Skipped some archives:';
-    echo "${skip[@]}";
-fi;
+    warn 'Skipped some archives:'
+    echo "${skip[@]}"
+fi
 
-exit 0;
+exit 0
